source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'xcPetalV3' do
    pod 'AWSIoT', '~>2.5.0'
    pod 'SwiftyJSON'
    pod 'CircularSlider'
    pod 'SwiftyTimer'
end
