source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'IoTSampleSwift' do
    pod 'AWSIoT', '~>2.5.0'
    pod 'AWSAutoScaling'
	pod 'AWSCloudWatch'
	pod 'AWSCognito'
	pod 'AWSCognitoIdentityProvider'
	pod 'AWSDynamoDB'
	pod 'AWSEC2'
	pod 'AWSElasticLoadBalancing'
	pod 'AWSKinesis'
	pod 'AWSLambda'
	pod 'AWSMachineLearning'
	pod 'AWSMobileAnalytics'
	pod 'AWSS3'
	pod 'AWSSES'
	pod 'AWSSimpleDB'
	pod 'AWSSNS'
	pod 'AWSSQS'
end
